version: '3.8'
services:
  db:
    image: postgres:12.3
    restart: always
    ports:
      - 5102:5432
    environment:
      - POSTGRES_USER=${POSTGRESQL_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_DATABASE}
    env_file:
      - .env
    volumes:
      - ./.db:/var/lib/postgresql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: "mix phx.server --no-halt"
    restart: always
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    ports:
       - 4101:4101

networks:
  default:
    external:
      name: web_tree_crawler_network
